#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

echo "[*] Building release manifest..."
python3 tools/build_release_manifest.py

echo "[*] Stamping release manifest with OpenTimestamps..."
bash tools/stamp_manifest_ots.sh

echo "[*] Writing GitHub Actions receipt..."
python3 tools/write_github_actions_receipt.py

echo "[*] Local verification..."

if [[ -n "${OTS_BIN:-}" && -x "${OTS_BIN:-}" ]]; then
  FOUND_OTS="$OTS_BIN"
elif command -v ots >/dev/null 2>&1; then
  FOUND_OTS="$(command -v ots)"
elif command -v pyenv >/dev/null 2>&1 && pyenv which ots >/dev/null 2>&1; then
  FOUND_OTS="$(pyenv which ots)"
else
  FOUND_OTS=""
fi

if [[ -n "$FOUND_OTS" ]]; then
  python3 tools/verify_stage264_anchor.py --dir out/release --ots-bin "$FOUND_OTS"
else
  python3 tools/verify_stage264_anchor.py --dir out/release
fi

echo "[*] Preparing Pages bundle..."
python3 tools/write_pages_bundle.py

echo "[*] Ensuring HTML files exist in Pages output..."

mkdir -p site

cat > site/index.html << 'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Stage265 Public Verification URL</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 2rem;
      line-height: 1.6;
      max-width: 900px;
    }
    .card {
      border: 1px solid #ddd;
      border-radius: 10px;
      padding: 1rem;
      margin-bottom: 1rem;
    }
    code, pre {
      background: #f5f5f5;
      padding: 0.2rem 0.4rem;
      border-radius: 4px;
    }
    a { word-break: break-all; }
  </style>
</head>
<body>
  <h1>Stage265 Public Verification URL</h1>

  <div class="card">
    <p>
      This page publishes the Stage265 browser-based verification entry point.
    </p>
    <p>
      Main verifier:
      <a href="./verify.html">verify.html</a>
    </p>
  </div>

  <div class="card">
    <h2>Purpose</h2>
    <ul>
      <li>Public verification via URL</li>
      <li>No local execution required for basic checks</li>
      <li>Manifest / SHA256 / receipt consistency checks in browser</li>
      <li>Designed to align with public evidence verification expectations</li>
    </ul>
  </div>

  <div class="card">
    <h2>Expected files</h2>
    <pre>
release_manifest.json
release_manifest.json.sha256
release_manifest.json.ots
github_actions_receipt.json
stage265-source-bundle.tar.gz
    </pre>
  </div>
</body>
</html>
HTML

cat > site/verify.html << 'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Stage265 Public Verification URL</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 2rem;
      line-height: 1.6;
      max-width: 900px;
    }
    h1, h2 {
      margin-bottom: 0.5rem;
    }
    .card {
      border: 1px solid #ddd;
      border-radius: 10px;
      padding: 1rem;
      margin-bottom: 1rem;
    }
    .ok { color: #0a7a2f; font-weight: bold; }
    .warn { color: #b36b00; font-weight: bold; }
    .err { color: #b00020; font-weight: bold; }
    code, pre {
      background: #f5f5f5;
      padding: 0.2rem 0.4rem;
      border-radius: 4px;
      overflow-x: auto;
    }
    pre { padding: 1rem; }
    a { word-break: break-all; }
  </style>
</head>
<body>
  <h1>Stage265 Public Verification URL</h1>
  <p>
    This page verifies a published evidence bundle generated by GitHub Actions.
  </p>

  <div class="card">
    <h2>Verification Result</h2>
    <div id="result">Loading...</div>
  </div>

  <div class="card">
    <h2>Loaded Files</h2>
    <ul id="files"></ul>
  </div>

  <div class="card">
    <h2>Raw Metadata</h2>
    <pre id="meta"></pre>
  </div>

  <script>
    async function sha256Hex(arrayBuffer) {
      const hashBuffer = await crypto.subtle.digest("SHA-256", arrayBuffer);
      return [...new Uint8Array(hashBuffer)].map(b => b.toString(16).padStart(2, "0")).join("");
    }

    function getParam(name, fallback) {
      const url = new URL(window.location.href);
      return url.searchParams.get(name) || fallback;
    }

    function addFile(name, href) {
      const li = document.createElement("li");
      const a = document.createElement("a");
      a.href = href;
      a.textContent = href;
      a.target = "_blank";
      li.textContent = name + ": ";
      li.appendChild(a);
      document.getElementById("files").appendChild(li);
    }

    function line(msg, cls) {
      return `<div class="${cls}">${msg}</div>`;
    }

    async function fetchText(path) {
      const res = await fetch(path, { cache: "no-store" });
      if (!res.ok) throw new Error(`Failed to fetch ${path}: ${res.status}`);
      return await res.text();
    }

    async function fetchArrayBuffer(path) {
      const res = await fetch(path, { cache: "no-store" });
      if (!res.ok) throw new Error(`Failed to fetch ${path}: ${res.status}`);
      return await res.arrayBuffer();
    }

    async function main() {
      const manifestPath = getParam("manifest", "release_manifest.json");
      const shaPath = getParam("sha256", "release_manifest.json.sha256");
      const receiptPath = getParam("receipt", "github_actions_receipt.json");
      const bundlePath = getParam("bundle", "stage265-source-bundle.tar.gz");
      const otsPath = getParam("ots", "release_manifest.json.ots");

      addFile("manifest", manifestPath);
      addFile("sha256", shaPath);
      addFile("receipt", receiptPath);
      addFile("bundle", bundlePath);
      addFile("ots", otsPath);

      const result = document.getElementById("result");
      const meta = document.getElementById("meta");

      try {
        const manifestText = await fetchText(manifestPath);
        const shaText = await fetchText(shaPath);
        const receiptText = await fetchText(receiptPath);
        const bundleBytes = await fetchArrayBuffer(bundlePath);

        const manifest = JSON.parse(manifestText);
        const receipt = JSON.parse(receiptText);

        const manifestHash = await sha256Hex(new TextEncoder().encode(manifestText));
        const bundleHash = await sha256Hex(bundleBytes);

        const shaLine = shaText.trim().split(/\s+/);
        const expectedManifestHash = shaLine[0];

        let expectedBundleHash = null;
        if (Array.isArray(manifest.artifacts) && manifest.artifacts.length > 0) {
          expectedBundleHash = manifest.artifacts[0].sha256;
        }

        let html = "";
        html += line("Stage265 verifier page loaded.", "ok");

        if (manifestHash === expectedManifestHash) {
          html += line(`Manifest SHA-256 verified: ${manifestHash}`, "ok");
        } else {
          html += line(`Manifest SHA-256 mismatch. expected=${expectedManifestHash} actual=${manifestHash}`, "err");
        }

        if (expectedBundleHash && bundleHash === expectedBundleHash) {
          html += line(`Bundle SHA-256 verified: ${bundleHash}`, "ok");
        } else if (expectedBundleHash) {
          html += line(`Bundle SHA-256 mismatch. expected=${expectedBundleHash} actual=${bundleHash}`, "err");
        } else {
          html += line("Bundle SHA-256 not found in manifest.", "warn");
        }

        const runUrl = receipt.github_actions && receipt.github_actions.run_url
          ? receipt.github_actions.run_url
          : "";
        if (runUrl) {
          html += line(`GitHub Actions run linked: ${runUrl}`, "ok");
        } else {
          html += line("GitHub Actions run URL not present in receipt.", "warn");
        }

        html += line(`OTS proof file detected: ${otsPath}`, "ok");
        html += line("Final Bitcoin confirmation still requires ots upgrade/verify outside the browser.", "warn");

        result.innerHTML = html;
        meta.textContent = JSON.stringify({ manifest, receipt }, null, 2);
      } catch (err) {
        result.innerHTML = line(`Verification failed: ${err.message}`, "err");
        meta.textContent = String(err.stack || err);
      }
    }

    main();
  </script>
</body>
</html>
HTML

echo "[OK] HTML files ensured in site/"
echo "[OK] Stage265 public verification flow completed"
